volumes:
  sniffer:
    driver: local
    driver_opts:
      device: /home/ubuntu/mqtt-sniffer/sniffer
      type: none
      o: bind
  data-dog-logs-synchronizer:
    driver: local
    driver_opts:
      device: /home/ubuntu/mqtt-sniffer/data-dog-logs-synchronizer
      type: none
      o: bind
  certificate:
    driver: local
    driver_opts:
      device: /home/ubuntu/mqtt-sniffer/certificate
      type: none
      o: bind
  logs:
    driver: local
    driver_opts:
      device: /home/ubuntu/mqtt-sniffer/logs
      type: none
      o: bind

services:
  sniffer:
    build: ./sniffer
    volumes:
      - sniffer:/mqtt-sniffer/app
      - certificate:/mqtt-sniffer/certificate
      - logs:/mqtt-sniffer/logs
  data-dog-logs-synchronizer:
    build: ./data-dog-logs-synchronizer
    volumes:
      - data-dog-logs-synchronizer:/data-dog-logs-synchronizer/app
      - logs:/data-dog-logs-synchronizer/logs